title: "Libuše Hannah Vepřek"
description: "Cultural anthropologist and computer scientist at the University of Tübingen."
theme: minima
markdown: kramdown

minima:
  social_links:
    github: LVep
  # Move navigation outside social_links block
navigation:
  - title: "Home"
    url: "/"
  - title: "CV"
    url: "/cv/"
  - title: "Publications"
    url: "/publications/"
